### PR TITLE
fix(sync/l2): check that downloaded blocks are L1/L2 accepted

### LINKED ISSUE #559: Audit gateway block status before accepting
The gateway has a large enum of possible block status'. We currently don't check this status and assume it is either `ACCEPTED_ON_L1` or `ACCEPTED_ON_L2`. This is because we assumed the queries we make wouldn't allow the gateway to return any unaccepted block.

A recent bug on the gateway has caused some blocks to return `REVERTED` as the status. Although this is a gateway bug; the only reason we currently did not incorrectly consume these blocks is because it was also missing the receipts field -- which luckily caused us to abort due to a parsing failure.

We should check the block status' and only accept marked as valid.

### PR DESCRIPTION
**Pull request by kkovaacs**
To avoid issues like we had past week (where a REVERTED block showed up
on Starknet testnet and we only failed to commit on it because it was
missing transaction receipts) this change adds an explicit check on the
block status: we only ever want to process L1 or L2 accepted blocks.

Fixes #559.

### CODE REVIEW

File: crates/pathfinder/src/state/sync/l2.rs [hunk 1]
```diff
@@ -269,7 +269,13 @@ async fn download_block(
                 let block_number = block.block_number;
                 tracing::warn!(?block_number, block_hash = ?expected_block_hash, "Block hash mismatch");
             }
-            Ok(DownloadBlock::Block(block))
+            match block.status {
+                Status::AcceptedOnL1 | Status::AcceptedOnL2 => Ok(DownloadBlock::Block(block)),
+                _ => Err(anyhow!(
+                    "Non-accepted block with state {} cannot be on chain",
```
[the remark this answers is not in the document]
Comment (Mirko-von-Leipzig) [reply crates/pathfinder/src/state/sync/l2.rs:275]: Or maybe some variation of:
```rust
"Rejecting block as its status is {}, and only accepted blocks are allowed."
```
Struggling to find a good phrasing :)

**Review by Mirko-von-Leipzig — APPROVED** [review]

**Review by koivunej — APPROVED** [review]

File: crates/pathfinder/src/state/sync/l2.rs (hunk 1 above)
Comment (CHr15F0x) [inline crates/pathfinder/src/state/sync/l2.rs:275]: Maybe even shorter?

```suggestion
                    "Block with status {} cannot be on chain",
```

File: crates/pathfinder/src/sequencer/reply.rs [hunk 2]
```diff
@@ -124,6 +124,21 @@ pub enum Status {
     Aborted,
 }
 
+impl std::fmt::Display for Status {
```
Comment (CHr15F0x) [inline crates/pathfinder/src/sequencer/reply.rs:127]: Hmm this kinda calls for `derive_more`, if we can accept another dependency...

**Review by CHr15F0x — APPROVED** [review]
Cool, LGTM

File: crates/pathfinder/src/sequencer/reply.rs (hunk 2 above)
Comment (kkovaacs) [reply crates/pathfinder/src/sequencer/reply.rs:127]: Thought of that but didn't want to add a new dependency just for this single case.
