### PR TITLE
fix(validator): handle deferred `TransactionsFin` properly

### LINKED ISSUE #3090: fix(validator): Does `TransactionsFin` processing fail when transactions are deferred?
I'm not sure this will work right now...

When tx's are deferred, they'll be put in `deferred_executions`, so no execution state is created.

When `TransactionsFin` arrives, `process_transactions_fin` will return an error because no execution state will be found.

We should probably defer `TransactionsFin` message when transactions are deferred.

Noting to investigate further...

### PR DESCRIPTION
**Pull request by t00ts**
`TransactionFin` and deferral were not getting along well (as [suspected](https://github.com/eqlabs/pathfinder/issues/3090)).

This PR fixes that and in general I've paid more attention to all the deferred path.

--

Pretty much rewrote the whole batch executor test suite to make it as robust as I possibly could:

- Deferral: Transactions deferred when parent not committed
- Immediate Execution: Transactions execute when parent committed
- Deferred Execution: Previously deferred transactions execute when parent becomes committed
- `TransactionsFin` Processing: Normal case (no rollback)
- `TransactionsFin` Rollback: Rollback when fewer transactions indicated
- `TransactionsFin` Deferral: Defer when execution hasn't started
- Deferred `TransactionsFin` Processing: Process deferred `TransactionsFin` when execution starts
- Multiple Batches: Handle multiple batches with deferral
- Empty Batch: Empty batch still marks execution as started

--

Closes #3090

### CODE REVIEW

File: crates/pathfinder/src/consensus/inner/batch_execution.rs [hunk 1]
```diff
@@ -21,16 +21,50 @@ pub struct BatchExecutionManager {
     /// An entry exists here if at least one batch has been executed (not
     /// deferred).
     executing: HashSet<HeightAndRound>,
+    /// Tracks which proposals (height/round) have had TransactionsFin
+    /// processed. An entry exists here if TransactionsFin has been
+    /// successfully processed for this height/round.
```
Comment (CHr15F0x) [inline crates/pathfinder/src/consensus/inner/batch_execution.rs:26]: I really like the way you comment code. It's all clear once I've read the comments.

File: crates/pathfinder/src/consensus/inner/batch_execution.rs [hunk 2]
```diff
@@ -84,10 +119,67 @@ impl BatchExecutionManager {
...
+    /// previously deferred transactions after the parent block is
+    /// committed).
+    pub fn execute_batch(
+        &mut self,
+        height_and_round: HeightAndRound,
+        transactions: Vec<proto_consensus::Transaction>,
+        validator: &mut ValidatorTransactionBatchStage,
+    ) -> anyhow::Result<()> {
+        // Mark that execution has started for this height/round, even if batch is
+        // empty. This is necessary because TransactionsFin may arrive later and
```
Comment (CHr15F0x) [inline crates/pathfinder/src/consensus/inner/batch_execution.rs:153]: [IIRC](https://github.com/starknet-io/starknet-p2p-specs/blob/main/p2p/proto/consensus/consensus.md) you should never get a transactions fin if batches were empty. Plus the spec does not allow empty batches... For now we allow them but maybe we should be stricter. Anyhow, I don't remember if we check all of those constraints correctly at the incoming message handler :thinking: . We should double check this.

File: crates/pathfinder/src/consensus/inner/batch_execution.rs [hunk 3]
```diff
@@ -119,21 +211,43 @@ impl BatchExecutionManager {
...
+            // we need to rollback to index N-1 (which keeps transactions 0 through N-1).
+            let target_index = target_transaction_count
+                .checked_sub(1)
+                .context("Cannot rollback to 0 transactions")?;
             validator
-                .rollback_to_transaction(target_transaction_count)
+                .rollback_to_transaction(target_index)
                 .context("Failed to rollback to target transaction count")?;
+        } else if target_transaction_count > current_transaction_count {
+            // This shouldn't happen with proper message ordering and no protocol errors.
```
Comment (CHr15F0x) [inline crates/pathfinder/src/consensus/inner/batch_execution.rs:224]: I wonder if `handle_incoming...` has a proper comment to then punish the peer which misbehaved.

File: crates/pathfinder/src/consensus/inner/batch_execution.rs (hunk 2 above)
Comment (t00ts) [reply crates/pathfinder/src/consensus/inner/batch_execution.rs:153]: Yeah, I admit I've stressed some paths over the spec itself, but don't think it hurts to account for these edge cases just in case 👍

File: crates/pathfinder/src/consensus/inner/batch_execution.rs (hunk 3 above)
Comment (t00ts) [reply crates/pathfinder/src/consensus/inner/batch_execution.rs:224]: There's no _missbehaviour_ here. It's just messages arriving in order (or not). `handle_incoming_proposal_message` just guarantees the consumer (us) gets them in order. Again, just left that for debugging purposes. If we ever get that warning we should pay attention to this, otherwise we'll prob never get that.

File: crates/pathfinder/src/consensus/inner/batch_execution.rs (hunk 1 above)
Comment (t00ts) [reply crates/pathfinder/src/consensus/inner/batch_execution.rs:26]: Thanks, I am a big fan of comments 🙂
