### PR TITLE
fix(rpc/v02): add optional token parameter to `starknet_addDeclareTransaction`

### LINKED ISSUE #678: Add optional `token` parameter to the version 0.2.1 `starknet_addDeclareTransaction` method
This is still missing from the method (but present in `starknet_addDeployTransaction`).

### PR DESCRIPTION
**Pull request by kkovaacs**
This is still required on Starknet mainnet according to Starkware.

Closes #678.

### CODE REVIEW

File: crates/pathfinder/src/rpc/v02/method/add_declare_transaction.rs [hunk 1]
```diff
@@ -147,7 +152,8 @@ mod tests {
                         "nonce": "0x0",
                         "contract_class": {},
                         "sender_address": "0x1"
-                    }}
+                    }},
+                    "token": "token"
```
Comment (sergey-melnychuk) [inline crates/pathfinder/src/rpc/v02/method/add_declare_transaction.rs:156]: Is `token` supported for named params only? If no, should `positional_args` test be also updated?

**Review by sergey-melnychuk — APPROVED** [review]
LGTM

File: crates/pathfinder/src/rpc/v02/method/add_declare_transaction.rs (hunk 1 above)
Comment (kkovaacs) [reply crates/pathfinder/src/rpc/v02/method/add_declare_transaction.rs:156]: I didn't update that test so that it tests that the parameter is optional. I wasn't very explicit, though...

**Review by CHr15F0x — APPROVED** [review]
