### PR TITLE
fix(rpc/get_compiled_casm): don't wrap CASM class in a `casm` property

### LINKED ISSUE #2635: `starknet_getCompiledCasm` returns CASM wrapped in a `casm` property
The [specs](https://github.com/starkware-libs/starknet-specs/blob/436e6307bab3938339e4bf469f14dee79b50802d/api/starknet_executables.json#L24) state that the class should be returned directly in the `result`.

### PR DESCRIPTION
**Pull request by kkovaacs**
According to the JSON-RPC 0.8.0-rc3 specs the output CASM class should not be wrapped inside a `casm` property.

This PR removes that additional wrapping.

Closes #2635

### CODE REVIEW

File: crates/rpc/src/method/get_compiled_casm.rs [hunk 1]
```diff
@@ -145,6 +144,20 @@ mod tests {
...
+    async fn serialization() {
+        let rpc = setup().await.unwrap();
+
+        let result = get_compiled_casm(rpc, input()).await.unwrap();
+        let output = crate::dto::SerializeForVersion::serialize(
+            &result,
+            crate::dto::Serializer::new(crate::RpcVersion::V08),
+        )
+        .unwrap();
+        let expected_output = serde_json::to_value(&expected()).unwrap();
```
Comment (vbar) [inline crates/rpc/src/method/get_compiled_casm.rs:157]:
```suggestion
        let expected_output = serde_json::to_value(expected()).unwrap();
```

**Review by vbar — APPROVED** [review]
