### PR TITLE
Chris/rpc v0.4 new error codes

### LINKED ISSUE #1283: RPC v0.4: add new error codes
Implement changes from [this PR](https://github.com/starkware-libs/starknet-specs/pull/119) that will be merged into v0.4.0 spec.

Additional reference - mapping by papyrus:

```
STARKNET_GATEWAY_ERROR -> JSON_RPC_ERROR
COMPILATION_FAILED -> COMPILATION_FAILED
CONTRACT_BYTECODE_SIZE_TOO_LARGE -> CONTRACT_CLASS_SIZE_TOO_LARGE
CONTRACT_CLASS_OBJECT_SIZE_TOO_LARGE -> CONTRACT_CLASS_SIZE_TOO_LARGE
DUPLICATED_TRANSACTION -> DUPLICATE_TX
INSUFFICIENT_ACCOUNT_BALANCE -> INSUFFICIENT_ACCOUNT_BALANCE
INSUFFICIENT_MAX_FEE -> INSUFFICIENT_MAX_FEE
INVALID_COMPILED_CLASS_HASH -> COMPILED_CLASS_HASH_MISMATCH
INVALID_TRANSACTION_NONCE -> INVALID_TRANSACTION_NONCE
VALIDATE_FAILURE -> VALIDATION_FAILURE
CLASS_ALREADY_DECLARED -> CLASS_ALREADY_DECLARED
INVALID_CONTRACT_CLASS_VERSION -> UNSUPPORTED_CONTRACT_CLASS_VERSION
INVALID_TRANSACTION_VERSION -> UNSUPPORTED_TX_VERSION
UNDECLARED_CLASS -> CLASS_HASH_NOT_FOUND
Every other error code goes to UNEXPECTED_ERROR
```

### PR DESCRIPTION
**Pull request by CHr15F0x**
Fixes #1283 

---------------------------

~~I'm unsure about [removing `InvalidMessageSelector`](https://github.com/eqlabs/pathfinder/pull/1289/commits/a2758fbe146bb3af51747a2ea8a8fe1e54951ce1) which was removed in v03 spec but is used in our version of v03 in call and estimate fee, which makes our impl deviate from the spec.
I don't know if any libs/services rely on that specific variant (but still this is a breaking change).~~
Edit: it's bug fix as we need to stick to the spec.

There's no such issue with the other removed variant as it was dead code.

### CODE REVIEW

File: crates/rpc/src/error.rs
Comment (CHr15F0x) [inline crates/rpc/src/error.rs:1]: I added these comments to keep sane while peeking at the spec(s) at the same time. Could be useful if splitting into two enums later on.

File: crates/rpc/src/v04/method/add_declare_transaction.rs [hunk 1]
```diff
@@ -407,7 +418,8 @@ mod tests {
             token: None,
         };
         let error = add_declare_transaction(context, input).await.unwrap_err();
-        assert_matches::assert_matches!(error, AddDeclareTransactionError::InvalidContractClass);
+        // assert_matches::assert_matches!(error, AddDeclareTransactionError::InvalidContractClass);
```
Comment (CHr15F0x) [inline crates/rpc/src/v04/method/add_declare_transaction.rs:421]: Whoopsie, sorry for the commented code in the tests.

**Review by Mirko-von-Leipzig — APPROVED** [review]

**Review by Mirko-von-Leipzig — APPROVED** [review]
